// Module included in the following assemblies:
//
// * installing/installing-vsphere-installer-provisioned-network-customizations.adoc

:_mod-docs-content-type: PROCEDURE
[id="installation-vsphere-multiple-nics_{context}"]
= Configuring multiple NICs

For scenarios requiring multiple NICs, {product-title} supports configuration of multiple network adapters per node. 

:FeatureName: Configuring multiple NICs
include::snippets/technology-preview.adoc[]

.Procedure

. Specify the network adapter names in the networks section of `platform.vsphere.failureDomains[*].topology` as shown in the following file:
+
[source,yaml]
----
platform:
  vsphere:
    vcenters:
      ...
    failureDomains:
    - name: <failure_domain_name>
      region: <default_region_name>
      zone: <default_zone_name>
      server: <fully_qualified_domain_name>
      topology:
        datacenter: <data_center>
        computeCluster: "/<data_center>/host/<cluster>"
        networks: # <1>
        - <VM_network1_name>
        - <VM_network2_name>
        - ...
        - <VM_network10_name>
----
<1> Specifies the list of network adapters. You can specify up to 10 network adapters.

. Specify at least one of the following configurations:

** `networking.machineNetwork`
+
.Example configuration
+
[source,yaml]
----
networking:
  ...
  machineNetwork:
  - cidr: 10.0.0.0/16
  ...
----
+
[NOTE]
====
The `networking.machineNetwork.cidr` must correspond to an address on the first adapter defined in `topology.networks`.
====

** `nodeNetworking`
+
.Example configuration
+
[source,yaml]
----
platform:
  vsphere:
    nodeNetworking:
     external:
       networkSubnetCidr:
       - <machine_network_cidr_ipv4>
       - <machine_network_cidr_ipv6>
     internal:
       networkSubnetCidr:
       - <machine_network_cidr_ipv4>
       - <machine_network_cidr_ipv6>
    failureDomains:
    - name: <failure_domain_name>
      region: <default_region_name>
----